#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Env
export EDITOR=vim
export LC_ALL=en_US.UTF-8

# Search history by prefix
bindkey "" history-beginning-search-backward
bindkey "^N" history-beginning-search-forward

# Aliases
alias c=cd
alias g=git
alias ga='git add'
alias gb='git branch'
alias gc='git commit -v'
alias gco='git checkout'
alias gd='git diff'
alias gf='git fetch'
alias gg='git grep'
alias gl='git pull'
alias gp='git push'
alias gs='git status'
alias j=jobs
alias l=ls
alias m=make
alias md='mkdir -p'
alias p=python
alias t=tree
alias tm=tmux
alias v=vim

# Path
export PATH=$HOME/bin:$PATH

# Automatically set env vars from .envrc
eval "$(direnv hook zsh)"

# Python
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# Ruby
source /usr/local/opt/chruby/share/chruby/chruby.sh
source /usr/local/opt/chruby/share/chruby/auto.sh

# Node
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Insert last arg by "ctrl-]"
autoload smart-insert-last-word
zle -N insert-last-word smart-insert-last-word
zstyle :insert-last-word match "*([^[:space:]][[:alpha:]/\\]|[[:alpha:]/\\][^[:space:]])*"
bindkey "^]" insert-last-word
